/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/esqueci-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Esqueci Senha
         * @description Começa a recuperação. Sempre 202, tenha o e-mail conta ou não.
         */
        post: operations["esqueciSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Usuario Atual
         * @description Rota protegida de referência: é o que o frontend chama ao abrir o app.
         */
        get: operations["obterUsuarioAtual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entrar */
        post: operations["entrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerrar Sessao
         * @description Encerra a sessão. Responde 204 mesmo com token já inválido: o fim é o mesmo.
         */
        post: operations["encerrarSessao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/redefinir-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redefinir Senha */
        post: operations["redefinirSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar Sessao */
        post: operations["renovarSessao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar Conta */
        post: operations["registrarConta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{provedor}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback Oauth
         * @description Recebe o provedor de volta, resolve a conta e devolve o aluno ao frontend.
         */
        get: operations["callbackOauth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{provedor}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Iniciar Login Social
         * @description Manda o aluno para o provedor.
         */
        get: operations["iniciarLoginSocial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Ranking */
        get: operations["obterRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trilhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo de trilhas
         * @description Trilhas publicadas, paginadas. Aceita `ordenar_por` em `periodo`, `nome` ou `disciplina`.
         */
        get: operations["listarTrilhas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trilhas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trilha com módulos e atividades */
        get: operations["obterTrilha"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Perfil */
        get: operations["obterPerfil"];
        put?: never;
        post?: never;
        /**
         * Excluir Minha Conta
         * @description Pede a exclusão da conta: desativa agora e apaga tudo no fim do prazo.
         *
         *     202 e não 204: o pedido foi aceito, mas a exclusão só se completa no expurgo.
         */
        delete: operations["excluirMinhaConta"];
        options?: never;
        head?: never;
        /** Atualizar Perfil */
        patch: operations["atualizarPerfil"];
        trace?: never;
    };
    "/api/v1/usuarios/me/dados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar Meus Dados
         * @description Tudo o que o Algorise guarda sobre o aluno, para baixar como arquivo.
         */
        get: operations["exportarMeusDados"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Processo vivo. Não toca no banco: é o healthcheck do container.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Pronta para servir: o banco respondeu.
         *
         *     Devolve 503 em vez de estourar exceção, para o orquestrador tirar a
         *     instância do balanceador sem a API cair.
         *
         *     O Redis aparece no corpo mas não muda o status: ele é cache, e sem ele a API
         *     continua servindo — tirar a instância do balanceador só pioraria as coisas.
         */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versao */
        get: operations["versao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AtividadeResumo
         * @description Atividade sem gabarito — é o que pode ir para o cliente.
         */
        AtividadeResumo: {
            /** Dica */
            dica?: string | null;
            /** Enunciado */
            enunciado: string;
            /** Id */
            id: number;
            /** Ordem */
            ordem: number;
            /** Tempo Sugerido Segundos */
            tempo_sugerido_segundos?: number | null;
            tipo: components["schemas"]["TipoAtividade"];
            /** Xp */
            xp: number;
        };
        /**
         * AtualizacaoPerfil
         * @description PATCH parcial: só os campos enviados mudam.
         *
         *     Instituição e curso vêm por nome, como o aluno digitou no onboarding; o
         *     backend reaproveita o registro existente ou cria um novo.
         */
        AtualizacaoPerfil: {
            /** Curso */
            curso?: string | null;
            /** Instituicao */
            instituicao?: string | null;
            nivel_experiencia?: components["schemas"]["NivelExperiencia"] | null;
            /** Nome Exibicao */
            nome_exibicao?: string | null;
            /** Periodo */
            periodo?: number | null;
            tipo_trilha?: components["schemas"]["TipoTrilha"] | null;
        };
        /**
         * EntradaRanking
         * @description Uma linha do pódio ou da lista rolável (telas 16 e 17).
         */
        EntradaRanking: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Nome Exibicao */
            nome_exibicao: string;
            /** Posicao */
            posicao: number;
            /** Username */
            username: string;
            /** Usuario Id */
            usuario_id: number;
            /** Xp */
            xp: number;
        };
        /**
         * Erro
         * @description O conteúdo do campo `erro`.
         */
        Erro: {
            /**
             * Code
             * @description Código estável; é nele que o código do cliente decide
             */
            code: string;
            /**
             * Details
             * @description O que é específico deste erro, como o campo que falhou
             */
            details?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description Mensagem em português, para mostrar ao aluno
             */
            message: string;
            /**
             * Request Id
             * @description Id da requisição, o mesmo que aparece no log
             */
            request_id?: string | null;
        };
        /** EsqueciSenha */
        EsqueciSenha: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ExclusaoAgendada */
        ExclusaoAgendada: {
            /** Detail */
            detail: string;
            /**
             * Exclusao Agendada Para
             * Format: date-time
             */
            exclusao_agendada_para: string;
        };
        /**
         * ExclusaoConta
         * @description Corpo do `DELETE /usuarios/me`.
         */
        ExclusaoConta: {
            /** Confirmacao */
            confirmacao: string;
            /** Senha */
            senha?: string | null;
        };
        /** Login */
        Login: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Lembrar
             * @default false
             */
            lembrar: boolean;
            /** Senha */
            senha: string;
        };
        /** ModuloDetalhe */
        ModuloDetalhe: {
            /**
             * Atividades
             * @default []
             */
            atividades: components["schemas"]["AtividadeResumo"][];
            /**
             * Bloqueado
             * @default true
             */
            bloqueado: boolean;
            /**
             * Concluido
             * @default false
             */
            concluido: boolean;
            /** Descricao */
            descricao?: string | null;
            /** Id */
            id: number;
            /** Ordem */
            ordem: number;
            /** Titulo */
            titulo: string;
            /** Video Url */
            video_url?: string | null;
        };
        /**
         * NivelExperiencia
         * @description Perfil escolhido no onboarding (telas 7 a 9).
         * @enum {string}
         */
        NivelExperiencia: "baixo" | "medio" | "alto";
        /** Pagina[Trilha] */
        Pagina_Trilha_: {
            /** Itens */
            itens: components["schemas"]["Trilha"][];
            /**
             * Pagina
             * @description Página atual, começando em 1
             */
            pagina: number;
            /**
             * Tamanho Pagina
             * @description Quantos itens cabem na página
             */
            tamanho_pagina: number;
            /**
             * Total
             * @description Total de itens em todas as páginas
             */
            total: number;
            /**
             * Total Paginas
             * @description Quantas páginas existem no total
             */
            total_paginas: number;
        };
        /**
         * Perfil
         * @description Tudo o que as telas privadas mostram do aluno.
         *
         *     Mais completo que o `UsuarioAutenticado` do login: traz o que o onboarding
         *     coletou e o streak, que o `/auth/eu` não precisa carregar.
         */
        Perfil: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Curso */
            curso?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /** Instituicao */
            instituicao?: string | null;
            nivel_experiencia: components["schemas"]["NivelExperiencia"];
            /** Nome Exibicao */
            nome_exibicao: string;
            /** Periodo */
            periodo?: number | null;
            /**
             * Streak Dias
             * @default 0
             */
            streak_dias: number;
            /**
             * Tem Senha
             * @default false
             */
            tem_senha: boolean;
            tipo_trilha: components["schemas"]["TipoTrilha"];
            /** Username */
            username: string;
            /**
             * Xp Total
             * @default 0
             */
            xp_total: number;
        };
        /** Ranking */
        Ranking: {
            /** Lista */
            lista: components["schemas"]["EntradaRanking"][];
            /** Podio */
            podio: components["schemas"]["EntradaRanking"][];
            /** Total */
            total: number;
            usuario?: components["schemas"]["EntradaRanking"] | null;
        };
        /** RedefinirSenha */
        RedefinirSenha: {
            /** Senha */
            senha: string;
            /** Token */
            token: string;
        };
        /** Registro */
        Registro: {
            /**
             * Aceite Termos
             * @default false
             */
            aceite_termos: boolean;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Nome Exibicao */
            nome_exibicao?: string | null;
            /** Senha */
            senha: string;
            /** Username */
            username?: string | null;
        };
        /**
         * Renovacao
         * @description Corpo do refresh e do logout: os dois recebem o refresh token.
         */
        Renovacao: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RespostaDeErro
         * @description Corpo de qualquer resposta de erro. Existe para o OpenAPI documentá-lo.
         */
        RespostaDeErro: {
            erro: components["schemas"]["Erro"];
        };
        /** Sessao */
        Sessao: {
            /** Access Token */
            access_token: string;
            /** Aviso */
            aviso?: string | null;
            /** Expira Em */
            expira_em: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            usuario: components["schemas"]["UsuarioAutenticado"];
        };
        /**
         * TipoAtividade
         * @description Formato da atividade dentro de um módulo (telas 28 a 34).
         * @enum {string}
         */
        TipoAtividade: "terminal" | "resposta-aberta" | "multipla-escolha" | "ordenacao" | "preencher-lacuna" | "desafio-codigo";
        /**
         * TipoTrilha
         * @description Modalidade de trilha (telas 10 a 13).
         * @enum {string}
         */
        TipoTrilha: "guiada" | "livre" | "mista";
        /** Trilha */
        Trilha: {
            /** Categoria */
            categoria?: string | null;
            /** Disciplina */
            disciplina: string;
            /** Id */
            id: number;
            /** Nome */
            nome: string;
            /** Periodo */
            periodo?: number | null;
            /**
             * Progresso
             * @default 0
             */
            progresso: number;
            /** Slug */
            slug: string;
            /**
             * Total Modulos
             * @default 0
             */
            total_modulos: number;
        };
        /** TrilhaDetalhe */
        TrilhaDetalhe: {
            /** Categoria */
            categoria?: string | null;
            /** Descricao */
            descricao?: string | null;
            /** Disciplina */
            disciplina: string;
            /** Id */
            id: number;
            /**
             * Modulos
             * @default []
             */
            modulos: components["schemas"]["ModuloDetalhe"][];
            /** Nome */
            nome: string;
            /** Periodo */
            periodo?: number | null;
            /**
             * Progresso
             * @default 0
             */
            progresso: number;
            /** Slug */
            slug: string;
            /**
             * Total Modulos
             * @default 0
             */
            total_modulos: number;
        };
        /**
         * UsuarioAutenticado
         * @description O aluno como as telas privadas o veem.
         */
        UsuarioAutenticado: {
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /** Nome Exibicao */
            nome_exibicao: string;
            /**
             * Tem Senha
             * @default false
             */
            tem_senha: boolean;
            /** Username */
            username: string;
            /**
             * Xp Total
             * @default 0
             */
            xp_total: number;
        };
        /** Versao */
        Versao: {
            /** Ambiente */
            ambiente: string;
            /** Build */
            build?: string | null;
            /** Commit */
            commit: string;
            /** Nome */
            nome: string;
            /** Versao */
            versao: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    esqueciSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EsqueciSenha"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    obterUsuarioAtual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioAutenticado"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    entrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    encerrarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Renovacao"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    redefinirSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedefinirSenha"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    renovarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Renovacao"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    registrarConta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Registro"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    callbackOauth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provedor: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    iniciarLoginSocial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provedor: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    obterRanking: {
        parameters: {
            query?: {
                /** @description Tamanho da página */
                limite?: number;
                /** @description Quantos pular na lista rolável */
                deslocamento?: number;
                /** @description Aluno cuja posição também entra */
                usuario_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    listarTrilhas: {
        parameters: {
            query?: {
                /** @description Filtra por nome ou disciplina */
                busca?: string | null;
                /** @description Período letivo */
                periodo?: number | null;
                /** @description Página, começando em 1 */
                pagina?: number;
                /** @description Itens por página (máximo 100) */
                tamanho_pagina?: number;
                /** @description Campo de ordenação; cada rota documenta os seus */
                ordenar_por?: string | null;
                /** @description Inverte a ordem */
                decrescente?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Trilha_"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    obterTrilha: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrilhaDetalhe"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    obterPerfil: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    excluirMinhaConta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExclusaoConta"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExclusaoAgendada"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    atualizarPerfil: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizacaoPerfil"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    exportarMeusDados: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
    versao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Versao"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDeErro"];
                };
            };
        };
    };
}
