"""schema inicial

Revision ID: 69d2aaaacc82
Revises: 
Create Date: 2026-09-20 22:17:36.365050
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '69d2aaaacc82'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instituicoes')),
    sa.UniqueConstraint('nome', name=op.f('uq_instituicoes_nome'))
    )
    op.create_index(op.f('ix_instituicoes_sigla'), 'instituicoes', ['sigla'], unique=False)
    op.create_table('trilhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('disciplina', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trilhas')),
    sa.UniqueConstraint('slug', name=op.f('uq_trilhas_slug'))
    )
    op.create_index(op.f('ix_trilhas_periodo'), 'trilhas', ['periodo'], unique=False)
    op.create_index(op.f('ix_trilhas_publicada'), 'trilhas', ['publicada'], unique=False)
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('total_periodos', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], name=op.f('fk_cursos_instituicao_id_instituicoes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cursos')),
    sa.UniqueConstraint('instituicao_id', 'nome', name='uq_cursos_instituicao_nome')
    )
    op.create_index(op.f('ix_cursos_instituicao_id'), 'cursos', ['instituicao_id'], unique=False)
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trilha_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilhas.id'], name=op.f('fk_modulos_trilha_id_trilhas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modulos')),
    sa.UniqueConstraint('trilha_id', 'ordem', name='uq_modulos_trilha_ordem')
    )
    op.create_index(op.f('ix_modulos_trilha_id'), 'modulos', ['trilha_id'], unique=False)
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('terminal', 'resposta-aberta', 'multipla-escolha', 'ordenacao', 'preencher-lacuna', 'desafio-codigo', name='tipoatividade'), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('dica', sa.Text(), nullable=True),
    sa.Column('comando_esperado', sa.String(length=500), nullable=True),
    sa.Column('saida_esperada', sa.Text(), nullable=True),
    sa.Column('resposta_esperada', sa.Text(), nullable=True),
    sa.Column('tempo_sugerido_segundos', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], name=op.f('fk_atividades_modulo_id_modulos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atividades')),
    sa.UniqueConstraint('modulo_id', 'ordem', name='uq_atividades_modulo_ordem')
    )
    op.create_index(op.f('ix_atividades_modulo_id'), 'atividades', ['modulo_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('nivel_experiencia', sa.Enum('baixo', 'medio', 'alto', name='nivelexperiencia'), nullable=False),
    sa.Column('tipo_trilha', sa.Enum('guiada', 'livre', 'mista', name='tipotrilha'), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], name=op.f('fk_usuarios_curso_id_cursos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], name=op.f('fk_usuarios_instituicao_id_instituicoes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    sa.UniqueConstraint('username', name=op.f('uq_usuarios_username'))
    )
    op.create_index(op.f('ix_usuarios_xp_total'), 'usuarios', ['xp_total'], unique=False)
    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('trilha_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('parceiro', sa.String(length=120), nullable=True),
    sa.Column('emitido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilhas.id'], name=op.f('fk_certificados_trilha_id_trilhas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_certificados_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificados')),
    sa.UniqueConstraint('codigo', name=op.f('uq_certificados_codigo'))
    )
    op.create_index(op.f('ix_certificados_usuario_id'), 'certificados', ['usuario_id'], unique=False)
    op.create_table('ementas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'processando', 'processada', 'falhou', name='statusementa'), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], name=op.f('fk_ementas_curso_id_cursos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_ementas_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ementas'))
    )
    op.create_index(op.f('ix_ementas_status'), 'ementas', ['status'], unique=False)
    op.create_index(op.f('ix_ementas_usuario_id'), 'ementas', ['usuario_id'], unique=False)
    op.create_table('progresso_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('trilha_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('bloqueado', 'em-andamento', 'concluido', name='statusprogresso'), nullable=False),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], name=op.f('fk_progresso_usuario_modulo_id_modulos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilhas.id'], name=op.f('fk_progresso_usuario_trilha_id_trilhas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_progresso_usuario_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progresso_usuario')),
    sa.UniqueConstraint('usuario_id', 'modulo_id', name='uq_progresso_usuario_modulo')
    )
    op.create_index('ix_progresso_usuario_trilha', 'progresso_usuario', ['usuario_id', 'trilha_id'], unique=False)
    op.create_table('respostas_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('tentativa', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('tempo_gasto_segundos', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], name=op.f('fk_respostas_usuario_atividade_id_atividades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_respostas_usuario_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_respostas_usuario'))
    )
    op.create_index('ix_respostas_usuario_atividade', 'respostas_usuario', ['usuario_id', 'atividade_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dias_consecutivos', sa.Integer(), nullable=False),
    sa.Column('maior_sequencia', sa.Integer(), nullable=False),
    sa.Column('ultimo_acesso', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_streaks_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streaks')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_streaks_usuario_id'))
    )
    op.create_table('xp_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Enum('atividade', 'modulo', 'trilha', 'desafio', name='origemxp'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_xp_eventos_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_eventos'))
    )
    op.create_index('ix_xp_eventos_usuario_data', 'xp_eventos', ['usuario_id', 'criado_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_xp_eventos_usuario_data', table_name='xp_eventos')
    op.drop_table('xp_eventos')
    op.drop_table('streaks')
    op.drop_index('ix_respostas_usuario_atividade', table_name='respostas_usuario')
    op.drop_table('respostas_usuario')
    op.drop_index('ix_progresso_usuario_trilha', table_name='progresso_usuario')
    op.drop_table('progresso_usuario')
    op.drop_index(op.f('ix_ementas_usuario_id'), table_name='ementas')
    op.drop_index(op.f('ix_ementas_status'), table_name='ementas')
    op.drop_table('ementas')
    op.drop_index(op.f('ix_certificados_usuario_id'), table_name='certificados')
    op.drop_table('certificados')
    op.drop_index(op.f('ix_usuarios_xp_total'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_atividades_modulo_id'), table_name='atividades')
    op.drop_table('atividades')
    op.drop_index(op.f('ix_modulos_trilha_id'), table_name='modulos')
    op.drop_table('modulos')
    op.drop_index(op.f('ix_cursos_instituicao_id'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_trilhas_publicada'), table_name='trilhas')
    op.drop_index(op.f('ix_trilhas_periodo'), table_name='trilhas')
    op.drop_table('trilhas')
    op.drop_index(op.f('ix_instituicoes_sigla'), table_name='instituicoes')
    op.drop_table('instituicoes')
    # ### end Alembic commands ###

    # O autogenerate não remove os tipos ENUM: sem isto, `downgrade base`
    # seguido de `upgrade head` falha com "type already exists".
    for tipo in (
        "tipoatividade",
        "nivelexperiencia",
        "tipotrilha",
        "statusementa",
        "statusprogresso",
        "origemxp",
    ):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
