"""identidades oauth

Revision ID: 99560984814d
Revises: 69d2aaaacc82
Create Date: 2026-09-29 15:33:47.639778
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '99560984814d'
down_revision: str | None = '69d2aaaacc82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identidades_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('provedor', sa.Enum('github', 'google', name='provedoroauth'), nullable=False),
    sa.Column('id_externo', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_identidades_oauth_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identidades_oauth')),
    sa.UniqueConstraint('provedor', 'id_externo', name='uq_identidades_oauth_provedor_externo'),
    sa.UniqueConstraint('usuario_id', 'provedor', name='uq_identidades_oauth_usuario_provedor')
    )
    op.create_index(op.f('ix_identidades_oauth_usuario_id'), 'identidades_oauth', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identidades_oauth_usuario_id'), table_name='identidades_oauth')
    op.drop_table('identidades_oauth')
    # ### end Alembic commands ###

    # O autogenerate não remove o ENUM; sem isso o próximo upgrade falha com
    # "type provedoroauth already exists".
    op.execute("DROP TYPE IF EXISTS provedoroauth")
