"""consentimentos e exclusao de conta

Revision ID: b5cf497366ef
Revises: b7c1e2f3a4d5
Create Date: 2026-09-29 17:29:35.504292
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5cf497366ef'
down_revision: str | None = 'b7c1e2f3a4d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('versao_termos', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('aceito_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_consentimentos_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consentimentos'))
    )
    op.create_index(op.f('ix_consentimentos_usuario_id'), 'consentimentos', ['usuario_id'], unique=False)
    op.add_column('usuarios', sa.Column('exclusao_agendada_para', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_usuarios_exclusao_agendada_para'), 'usuarios', ['exclusao_agendada_para'], unique=False)
    # ### end Alembic commands ###

    # Toda tabela nova entra com RLS (ver b7c1e2f3a4d5): no Supabase, sem isso
    # os consentimentos — com IP — ficariam legíveis pela chave anon.
    op.execute("ALTER TABLE consentimentos ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_exclusao_agendada_para'), table_name='usuarios')
    op.drop_column('usuarios', 'exclusao_agendada_para')
    op.drop_index(op.f('ix_consentimentos_usuario_id'), table_name='consentimentos')
    op.drop_table('consentimentos')
    # ### end Alembic commands ###
